name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier check
        run: npx prettier . --check
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
         image: sunkiller/scraper-backend
         registry: docker.io
         tags: sunkiller/scraper-backend:latest
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}